apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    env: prod
  name: prod-nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/prabhat2k15/nginx-k8s.git'
    path: deploy
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
